// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.xh.play.entities;

public final class Entities {
  private Entities() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_app.Update)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string url = 1;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <code>string url = 1;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>bool must = 2;</code>
     * @return The must.
     */
    boolean getMust();

    /**
     * <code>string appVer = 3;</code>
     * @return The appVer.
     */
    java.lang.String getAppVer();
    /**
     * <code>string appVer = 3;</code>
     * @return The bytes for appVer.
     */
    com.google.protobuf.ByteString
        getAppVerBytes();

    /**
     * <code>string describe = 4;</code>
     * @return The describe.
     */
    java.lang.String getDescribe();
    /**
     * <code>string describe = 4;</code>
     * @return The bytes for describe.
     */
    com.google.protobuf.ByteString
        getDescribeBytes();
  }
  /**
   * Protobuf type {@code proto_app.Update}
   */
  public static final class Update extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_app.Update)
      UpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Update.newBuilder() to construct.
    private Update(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Update() {
      url_ = "";
      appVer_ = "";
      describe_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Update();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Update(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 16: {

              must_ = input.readBool();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              appVer_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              describe_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xh.play.entities.Entities.internal_static_proto_app_Update_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xh.play.entities.Entities.internal_static_proto_app_Update_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xh.play.entities.Entities.Update.class, com.xh.play.entities.Entities.Update.Builder.class);
    }

    public static final int URL_FIELD_NUMBER = 1;
    private volatile java.lang.Object url_;
    /**
     * <code>string url = 1;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 1;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MUST_FIELD_NUMBER = 2;
    private boolean must_;
    /**
     * <code>bool must = 2;</code>
     * @return The must.
     */
    @java.lang.Override
    public boolean getMust() {
      return must_;
    }

    public static final int APPVER_FIELD_NUMBER = 3;
    private volatile java.lang.Object appVer_;
    /**
     * <code>string appVer = 3;</code>
     * @return The appVer.
     */
    @java.lang.Override
    public java.lang.String getAppVer() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVer_ = s;
        return s;
      }
    }
    /**
     * <code>string appVer = 3;</code>
     * @return The bytes for appVer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppVerBytes() {
      java.lang.Object ref = appVer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIBE_FIELD_NUMBER = 4;
    private volatile java.lang.Object describe_;
    /**
     * <code>string describe = 4;</code>
     * @return The describe.
     */
    @java.lang.Override
    public java.lang.String getDescribe() {
      java.lang.Object ref = describe_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        describe_ = s;
        return s;
      }
    }
    /**
     * <code>string describe = 4;</code>
     * @return The bytes for describe.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescribeBytes() {
      java.lang.Object ref = describe_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        describe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
      }
      if (must_ != false) {
        output.writeBool(2, must_);
      }
      if (!getAppVerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appVer_);
      }
      if (!getDescribeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, describe_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
      }
      if (must_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, must_);
      }
      if (!getAppVerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appVer_);
      }
      if (!getDescribeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, describe_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xh.play.entities.Entities.Update)) {
        return super.equals(obj);
      }
      com.xh.play.entities.Entities.Update other = (com.xh.play.entities.Entities.Update) obj;

      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (getMust()
          != other.getMust()) return false;
      if (!getAppVer()
          .equals(other.getAppVer())) return false;
      if (!getDescribe()
          .equals(other.getDescribe())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + MUST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMust());
      hash = (37 * hash) + APPVER_FIELD_NUMBER;
      hash = (53 * hash) + getAppVer().hashCode();
      hash = (37 * hash) + DESCRIBE_FIELD_NUMBER;
      hash = (53 * hash) + getDescribe().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xh.play.entities.Entities.Update parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xh.play.entities.Entities.Update parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xh.play.entities.Entities.Update parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xh.play.entities.Entities.Update parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xh.play.entities.Entities.Update parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xh.play.entities.Entities.Update parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xh.play.entities.Entities.Update parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xh.play.entities.Entities.Update parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xh.play.entities.Entities.Update parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xh.play.entities.Entities.Update parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xh.play.entities.Entities.Update parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xh.play.entities.Entities.Update parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xh.play.entities.Entities.Update prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_app.Update}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_app.Update)
        com.xh.play.entities.Entities.UpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xh.play.entities.Entities.internal_static_proto_app_Update_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xh.play.entities.Entities.internal_static_proto_app_Update_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xh.play.entities.Entities.Update.class, com.xh.play.entities.Entities.Update.Builder.class);
      }

      // Construct using com.xh.play.entities.Entities.Update.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        url_ = "";

        must_ = false;

        appVer_ = "";

        describe_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xh.play.entities.Entities.internal_static_proto_app_Update_descriptor;
      }

      @java.lang.Override
      public com.xh.play.entities.Entities.Update getDefaultInstanceForType() {
        return com.xh.play.entities.Entities.Update.getDefaultInstance();
      }

      @java.lang.Override
      public com.xh.play.entities.Entities.Update build() {
        com.xh.play.entities.Entities.Update result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xh.play.entities.Entities.Update buildPartial() {
        com.xh.play.entities.Entities.Update result = new com.xh.play.entities.Entities.Update(this);
        result.url_ = url_;
        result.must_ = must_;
        result.appVer_ = appVer_;
        result.describe_ = describe_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xh.play.entities.Entities.Update) {
          return mergeFrom((com.xh.play.entities.Entities.Update)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xh.play.entities.Entities.Update other) {
        if (other == com.xh.play.entities.Entities.Update.getDefaultInstance()) return this;
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.getMust() != false) {
          setMust(other.getMust());
        }
        if (!other.getAppVer().isEmpty()) {
          appVer_ = other.appVer_;
          onChanged();
        }
        if (!other.getDescribe().isEmpty()) {
          describe_ = other.describe_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xh.play.entities.Entities.Update parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xh.play.entities.Entities.Update) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>string url = 1;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string url = 1;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 1;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 1;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private boolean must_ ;
      /**
       * <code>bool must = 2;</code>
       * @return The must.
       */
      @java.lang.Override
      public boolean getMust() {
        return must_;
      }
      /**
       * <code>bool must = 2;</code>
       * @param value The must to set.
       * @return This builder for chaining.
       */
      public Builder setMust(boolean value) {
        
        must_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool must = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMust() {
        
        must_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object appVer_ = "";
      /**
       * <code>string appVer = 3;</code>
       * @return The appVer.
       */
      public java.lang.String getAppVer() {
        java.lang.Object ref = appVer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appVer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appVer = 3;</code>
       * @return The bytes for appVer.
       */
      public com.google.protobuf.ByteString
          getAppVerBytes() {
        java.lang.Object ref = appVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appVer = 3;</code>
       * @param value The appVer to set.
       * @return This builder for chaining.
       */
      public Builder setAppVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appVer = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppVer() {
        
        appVer_ = getDefaultInstance().getAppVer();
        onChanged();
        return this;
      }
      /**
       * <code>string appVer = 3;</code>
       * @param value The bytes for appVer to set.
       * @return This builder for chaining.
       */
      public Builder setAppVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object describe_ = "";
      /**
       * <code>string describe = 4;</code>
       * @return The describe.
       */
      public java.lang.String getDescribe() {
        java.lang.Object ref = describe_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          describe_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string describe = 4;</code>
       * @return The bytes for describe.
       */
      public com.google.protobuf.ByteString
          getDescribeBytes() {
        java.lang.Object ref = describe_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          describe_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string describe = 4;</code>
       * @param value The describe to set.
       * @return This builder for chaining.
       */
      public Builder setDescribe(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        describe_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string describe = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescribe() {
        
        describe_ = getDefaultInstance().getDescribe();
        onChanged();
        return this;
      }
      /**
       * <code>string describe = 4;</code>
       * @param value The bytes for describe to set.
       * @return This builder for chaining.
       */
      public Builder setDescribeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        describe_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_app.Update)
    }

    // @@protoc_insertion_point(class_scope:proto_app.Update)
    private static final com.xh.play.entities.Entities.Update DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xh.play.entities.Entities.Update();
    }

    public static com.xh.play.entities.Entities.Update getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Update>
        PARSER = new com.google.protobuf.AbstractParser<Update>() {
      @java.lang.Override
      public Update parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Update(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Update> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Update> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xh.play.entities.Entities.Update getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SplashOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto_app.Splash)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string images = 1;</code>
     * @return A list containing the images.
     */
    java.util.List<java.lang.String>
        getImagesList();
    /**
     * <code>repeated string images = 1;</code>
     * @return The count of images.
     */
    int getImagesCount();
    /**
     * <code>repeated string images = 1;</code>
     * @param index The index of the element to return.
     * @return The images at the given index.
     */
    java.lang.String getImages(int index);
    /**
     * <code>repeated string images = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the images at the given index.
     */
    com.google.protobuf.ByteString
        getImagesBytes(int index);
  }
  /**
   * Protobuf type {@code proto_app.Splash}
   */
  public static final class Splash extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto_app.Splash)
      SplashOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Splash.newBuilder() to construct.
    private Splash(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Splash() {
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Splash();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Splash(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                images_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              images_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          images_ = images_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xh.play.entities.Entities.internal_static_proto_app_Splash_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xh.play.entities.Entities.internal_static_proto_app_Splash_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xh.play.entities.Entities.Splash.class, com.xh.play.entities.Entities.Splash.Builder.class);
    }

    public static final int IMAGES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList images_;
    /**
     * <code>repeated string images = 1;</code>
     * @return A list containing the images.
     */
    public com.google.protobuf.ProtocolStringList
        getImagesList() {
      return images_;
    }
    /**
     * <code>repeated string images = 1;</code>
     * @return The count of images.
     */
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <code>repeated string images = 1;</code>
     * @param index The index of the element to return.
     * @return The images at the given index.
     */
    public java.lang.String getImages(int index) {
      return images_.get(index);
    }
    /**
     * <code>repeated string images = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the images at the given index.
     */
    public com.google.protobuf.ByteString
        getImagesBytes(int index) {
      return images_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < images_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, images_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < images_.size(); i++) {
          dataSize += computeStringSizeNoTag(images_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getImagesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xh.play.entities.Entities.Splash)) {
        return super.equals(obj);
      }
      com.xh.play.entities.Entities.Splash other = (com.xh.play.entities.Entities.Splash) obj;

      if (!getImagesList()
          .equals(other.getImagesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getImagesCount() > 0) {
        hash = (37 * hash) + IMAGES_FIELD_NUMBER;
        hash = (53 * hash) + getImagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xh.play.entities.Entities.Splash parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xh.play.entities.Entities.Splash parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xh.play.entities.Entities.Splash parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xh.play.entities.Entities.Splash parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xh.play.entities.Entities.Splash parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xh.play.entities.Entities.Splash parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xh.play.entities.Entities.Splash parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xh.play.entities.Entities.Splash parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xh.play.entities.Entities.Splash parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xh.play.entities.Entities.Splash parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xh.play.entities.Entities.Splash parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xh.play.entities.Entities.Splash parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xh.play.entities.Entities.Splash prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto_app.Splash}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto_app.Splash)
        com.xh.play.entities.Entities.SplashOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xh.play.entities.Entities.internal_static_proto_app_Splash_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xh.play.entities.Entities.internal_static_proto_app_Splash_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xh.play.entities.Entities.Splash.class, com.xh.play.entities.Entities.Splash.Builder.class);
      }

      // Construct using com.xh.play.entities.Entities.Splash.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xh.play.entities.Entities.internal_static_proto_app_Splash_descriptor;
      }

      @java.lang.Override
      public com.xh.play.entities.Entities.Splash getDefaultInstanceForType() {
        return com.xh.play.entities.Entities.Splash.getDefaultInstance();
      }

      @java.lang.Override
      public com.xh.play.entities.Entities.Splash build() {
        com.xh.play.entities.Entities.Splash result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xh.play.entities.Entities.Splash buildPartial() {
        com.xh.play.entities.Entities.Splash result = new com.xh.play.entities.Entities.Splash(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          images_ = images_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.images_ = images_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xh.play.entities.Entities.Splash) {
          return mergeFrom((com.xh.play.entities.Entities.Splash)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xh.play.entities.Entities.Splash other) {
        if (other == com.xh.play.entities.Entities.Splash.getDefaultInstance()) return this;
        if (!other.images_.isEmpty()) {
          if (images_.isEmpty()) {
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImagesIsMutable();
            images_.addAll(other.images_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xh.play.entities.Entities.Splash parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xh.play.entities.Entities.Splash) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          images_ = new com.google.protobuf.LazyStringArrayList(images_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string images = 1;</code>
       * @return A list containing the images.
       */
      public com.google.protobuf.ProtocolStringList
          getImagesList() {
        return images_.getUnmodifiableView();
      }
      /**
       * <code>repeated string images = 1;</code>
       * @return The count of images.
       */
      public int getImagesCount() {
        return images_.size();
      }
      /**
       * <code>repeated string images = 1;</code>
       * @param index The index of the element to return.
       * @return The images at the given index.
       */
      public java.lang.String getImages(int index) {
        return images_.get(index);
      }
      /**
       * <code>repeated string images = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the images at the given index.
       */
      public com.google.protobuf.ByteString
          getImagesBytes(int index) {
        return images_.getByteString(index);
      }
      /**
       * <code>repeated string images = 1;</code>
       * @param index The index to set the value at.
       * @param value The images to set.
       * @return This builder for chaining.
       */
      public Builder setImages(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 1;</code>
       * @param value The images to add.
       * @return This builder for chaining.
       */
      public Builder addImages(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 1;</code>
       * @param values The images to add.
       * @return This builder for chaining.
       */
      public Builder addAllImages(
          java.lang.Iterable<java.lang.String> values) {
        ensureImagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, images_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearImages() {
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 1;</code>
       * @param value The bytes of the images to add.
       * @return This builder for chaining.
       */
      public Builder addImagesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto_app.Splash)
    }

    // @@protoc_insertion_point(class_scope:proto_app.Splash)
    private static final com.xh.play.entities.Entities.Splash DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xh.play.entities.Entities.Splash();
    }

    public static com.xh.play.entities.Entities.Splash getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Splash>
        PARSER = new com.google.protobuf.AbstractParser<Splash>() {
      @java.lang.Override
      public Splash parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Splash(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Splash> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Splash> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xh.play.entities.Entities.Splash getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_app_Update_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_app_Update_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_app_Splash_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_app_Splash_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\tproto_app\"E\n\006Update\022\013\n\003" +
      "url\030\001 \001(\t\022\014\n\004must\030\002 \001(\010\022\016\n\006appVer\030\003 \001(\t\022" +
      "\020\n\010describe\030\004 \001(\t\"\030\n\006Splash\022\016\n\006images\030\001 " +
      "\003(\tB \n\024com.xh.play.entitiesB\010Entitiesb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_app_Update_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_app_Update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_app_Update_descriptor,
        new java.lang.String[] { "Url", "Must", "AppVer", "Describe", });
    internal_static_proto_app_Splash_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_app_Splash_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_app_Splash_descriptor,
        new java.lang.String[] { "Images", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
